module.exports = [
  {
    _id: "demo1",
    id: "demo1",
    country: "Germany",
    city: "Berlin",
    topic: "Weekend in Berlin",
    rate: 5,
    imagePath: "https://picsum.photos/seed/berlin-demo/600/400",
    content: "A simple public demo post showing a Berlin travel example.",
    subtitel: "Public demo item 1",
    date: "2026-03-31",
    creator: "demo-user-id",
    author: "Demo User",
  },
  {
    _id: "demo2",
    id: "demo2",
    country: "Spain",
    city: "Barcelona",
    topic: "City and Beach",
    rate: 4,
    imagePath: "https://picsum.photos/seed/barcelona-demo/600/400",
    content: "A second standard item for the public portfolio version.",
    subtitel: "Public demo item 2",
    date: "2026-03-31",
    creator: "demo-user-id",
    author: "Demo User",
  },
  {
    _id: "demo3",
    id: "demo3",
    country: "Italy",
    city: "Rome",
    topic: "Historic Places",
    rate: 5,
    imagePath: "https://picsum.photos/seed/rome-demo/600/400",
    content: "A third demo entry so the app always has visible content.",
    subtitel: "Public demo item 3",
    date: "2026-03-31",
    creator: "demo-user-id",
    author: "Demo User",
  },
];
